import React from "react";

const mockResponse = {
    "tracks": {
      "href": "https://api.spotify.com/v1/search?offset=0&limit=10&query=abba&type=track&locale=en-GB,en;q%3D0.9,pt-BR;q%3D0.8,pt;q%3D0.7,en-US;q%3D0.6",
      "limit": 10,
      "next": "https://api.spotify.com/v1/search?offset=10&limit=10&query=abba&type=track&locale=en-GB,en;q%3D0.9,pt-BR;q%3D0.8,pt;q%3D0.7,en-US;q%3D0.6",
      "offset": 0,
      "previous": null,
      "total": 114,
      "items": [
        {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV"
                },
                "href": "https://api.spotify.com/v1/artists/0LcJLqbBmaGUft1e9Mm8HV",
                "id": "0LcJLqbBmaGUft1e9Mm8HV",
                "name": "ABBA",
                "type": "artist",
                "uri": "spotify:artist:0LcJLqbBmaGUft1e9Mm8HV"
              }
            ],
            "available_markets": [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/1V6a99EbTTIegOhWoPxYI9"
            },
            "href": "https://api.spotify.com/v1/albums/1V6a99EbTTIegOhWoPxYI9",
            "id": "1V6a99EbTTIegOhWoPxYI9",
            "images": [
              {
                "height": 640,
                "width": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b27370f7a1b35d5165c85b95a0e0"
              },
              {
                "height": 300,
                "width": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e0270f7a1b35d5165c85b95a0e0"
              },
              {
                "height": 64,
                "width": 64,
                "url": "https://i.scdn.co/image/ab67616d0000485170f7a1b35d5165c85b95a0e0"
              }
            ],
            "is_playable": true,
            "name": "Arrival",
            "release_date": "1976",
            "release_date_precision": "year",
            "total_tracks": 12,
            "type": "album",
            "uri": "spotify:album:1V6a99EbTTIegOhWoPxYI9"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV"
              },
              "href": "https://api.spotify.com/v1/artists/0LcJLqbBmaGUft1e9Mm8HV",
              "id": "0LcJLqbBmaGUft1e9Mm8HV",
              "name": "ABBA",
              "type": "artist",
              "uri": "spotify:artist:0LcJLqbBmaGUft1e9Mm8HV"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "disc_number": 1,
          "duration_ms": 230400,
          "explicit": false,
          "external_ids": {
            "isrc": "SEAYD7601020"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/0GjEhVFGZW8afUYGChu3Rr"
          },
          "href": "https://api.spotify.com/v1/tracks/0GjEhVFGZW8afUYGChu3Rr",
          "id": "0GjEhVFGZW8afUYGChu3Rr",
          "is_local": false,
          "is_playable": true,
          "name": "Dancing Queen",
          "popularity": 87,
          "preview_url": null,
          "track_number": 2,
          "type": "track",
          "uri": "spotify:track:0GjEhVFGZW8afUYGChu3Rr"
        },
        {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV"
                },
                "href": "https://api.spotify.com/v1/artists/0LcJLqbBmaGUft1e9Mm8HV",
                "id": "0LcJLqbBmaGUft1e9Mm8HV",
                "name": "ABBA",
                "type": "artist",
                "uri": "spotify:artist:0LcJLqbBmaGUft1e9Mm8HV"
              }
            ],
            "available_markets": [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/7iLuHJkrb9KHPkMgddYigh"
            },
            "href": "https://api.spotify.com/v1/albums/7iLuHJkrb9KHPkMgddYigh",
            "id": "7iLuHJkrb9KHPkMgddYigh",
            "images": [
              {
                "height": 640,
                "width": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b273aa22899360d8ba6704732dec"
              },
              {
                "height": 300,
                "width": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e02aa22899360d8ba6704732dec"
              },
              {
                "height": 64,
                "width": 64,
                "url": "https://i.scdn.co/image/ab67616d00004851aa22899360d8ba6704732dec"
              }
            ],
            "is_playable": true,
            "name": "Voulez-Vous",
            "release_date": "1979",
            "release_date_precision": "year",
            "total_tracks": 13,
            "type": "album",
            "uri": "spotify:album:7iLuHJkrb9KHPkMgddYigh"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV"
              },
              "href": "https://api.spotify.com/v1/artists/0LcJLqbBmaGUft1e9Mm8HV",
              "id": "0LcJLqbBmaGUft1e9Mm8HV",
              "name": "ABBA",
              "type": "artist",
              "uri": "spotify:artist:0LcJLqbBmaGUft1e9Mm8HV"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "disc_number": 1,
          "duration_ms": 292613,
          "explicit": false,
          "external_ids": {
            "isrc": "SEAYD7901120"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/3vkQ5DAB1qQMYO4Mr9zJN6"
          },
          "href": "https://api.spotify.com/v1/tracks/3vkQ5DAB1qQMYO4Mr9zJN6",
          "id": "3vkQ5DAB1qQMYO4Mr9zJN6",
          "is_local": false,
          "is_playable": true,
          "name": "Gimme! Gimme! Gimme! (A Man After Midnight)",
          "popularity": 83,
          "preview_url": null,
          "track_number": 13,
          "type": "track",
          "uri": "spotify:track:3vkQ5DAB1qQMYO4Mr9zJN6"
        },
        {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV"
                },
                "href": "https://api.spotify.com/v1/artists/0LcJLqbBmaGUft1e9Mm8HV",
                "id": "0LcJLqbBmaGUft1e9Mm8HV",
                "name": "ABBA",
                "type": "artist",
                "uri": "spotify:artist:0LcJLqbBmaGUft1e9Mm8HV"
              }
            ],
            "available_markets": [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/3ZdkT5buYFi1WQaB0XNNtf"
            },
            "href": "https://api.spotify.com/v1/albums/3ZdkT5buYFi1WQaB0XNNtf",
            "id": "3ZdkT5buYFi1WQaB0XNNtf",
            "images": [
              {
                "height": 640,
                "width": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b2734d08fc99eff4ed52dfce91fa"
              },
              {
                "height": 300,
                "width": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e024d08fc99eff4ed52dfce91fa"
              },
              {
                "height": 64,
                "width": 64,
                "url": "https://i.scdn.co/image/ab67616d000048514d08fc99eff4ed52dfce91fa"
              }
            ],
            "is_playable": true,
            "name": "Super Trouper",
            "release_date": "1980",
            "release_date_precision": "year",
            "total_tracks": 12,
            "type": "album",
            "uri": "spotify:album:3ZdkT5buYFi1WQaB0XNNtf"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV"
              },
              "href": "https://api.spotify.com/v1/artists/0LcJLqbBmaGUft1e9Mm8HV",
              "id": "0LcJLqbBmaGUft1e9Mm8HV",
              "name": "ABBA",
              "type": "artist",
              "uri": "spotify:artist:0LcJLqbBmaGUft1e9Mm8HV"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "disc_number": 1,
          "duration_ms": 274466,
          "explicit": false,
          "external_ids": {
            "isrc": "SEAYD8001090"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/4euAGZTszWPrriggYK0HG9"
          },
          "href": "https://api.spotify.com/v1/tracks/4euAGZTszWPrriggYK0HG9",
          "id": "4euAGZTszWPrriggYK0HG9",
          "is_local": false,
          "is_playable": true,
          "name": "Lay All Your Love On Me",
          "popularity": 80,
          "preview_url": null,
          "track_number": 9,
          "type": "track",
          "uri": "spotify:track:4euAGZTszWPrriggYK0HG9"
        },
        {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV"
                },
                "href": "https://api.spotify.com/v1/artists/0LcJLqbBmaGUft1e9Mm8HV",
                "id": "0LcJLqbBmaGUft1e9Mm8HV",
                "name": "ABBA",
                "type": "artist",
                "uri": "spotify:artist:0LcJLqbBmaGUft1e9Mm8HV"
              }
            ],
            "available_markets": [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/1kM6xcSYO5ASJaWgygznL7"
            },
            "href": "https://api.spotify.com/v1/albums/1kM6xcSYO5ASJaWgygznL7",
            "id": "1kM6xcSYO5ASJaWgygznL7",
            "images": [
              {
                "height": 640,
                "width": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b27392d0747a634fcc351c6ac3c2"
              },
              {
                "height": 300,
                "width": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e0292d0747a634fcc351c6ac3c2"
              },
              {
                "height": 64,
                "width": 64,
                "url": "https://i.scdn.co/image/ab67616d0000485192d0747a634fcc351c6ac3c2"
              }
            ],
            "is_playable": true,
            "name": "Abba",
            "release_date": "1975",
            "release_date_precision": "year",
            "total_tracks": 13,
            "type": "album",
            "uri": "spotify:album:1kM6xcSYO5ASJaWgygznL7"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV"
              },
              "href": "https://api.spotify.com/v1/artists/0LcJLqbBmaGUft1e9Mm8HV",
              "id": "0LcJLqbBmaGUft1e9Mm8HV",
              "name": "ABBA",
              "type": "artist",
              "uri": "spotify:artist:0LcJLqbBmaGUft1e9Mm8HV"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "disc_number": 1,
          "duration_ms": 213266,
          "explicit": false,
          "external_ids": {
            "isrc": "SEAYD7501010"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/2TxCwUlqaOH3TIyJqGgR91"
          },
          "href": "https://api.spotify.com/v1/tracks/2TxCwUlqaOH3TIyJqGgR91",
          "id": "2TxCwUlqaOH3TIyJqGgR91",
          "is_local": false,
          "is_playable": true,
          "name": "Mamma Mia",
          "popularity": 81,
          "preview_url": null,
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:2TxCwUlqaOH3TIyJqGgR91"
        },
        {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV"
                },
                "href": "https://api.spotify.com/v1/artists/0LcJLqbBmaGUft1e9Mm8HV",
                "id": "0LcJLqbBmaGUft1e9Mm8HV",
                "name": "ABBA",
                "type": "artist",
                "uri": "spotify:artist:0LcJLqbBmaGUft1e9Mm8HV"
              }
            ],
            "available_markets": [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/3ZdkT5buYFi1WQaB0XNNtf"
            },
            "href": "https://api.spotify.com/v1/albums/3ZdkT5buYFi1WQaB0XNNtf",
            "id": "3ZdkT5buYFi1WQaB0XNNtf",
            "images": [
              {
                "height": 640,
                "width": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b2734d08fc99eff4ed52dfce91fa"
              },
              {
                "height": 300,
                "width": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e024d08fc99eff4ed52dfce91fa"
              },
              {
                "height": 64,
                "width": 64,
                "url": "https://i.scdn.co/image/ab67616d000048514d08fc99eff4ed52dfce91fa"
              }
            ],
            "is_playable": true,
            "name": "Super Trouper",
            "release_date": "1980",
            "release_date_precision": "year",
            "total_tracks": 12,
            "type": "album",
            "uri": "spotify:album:3ZdkT5buYFi1WQaB0XNNtf"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV"
              },
              "href": "https://api.spotify.com/v1/artists/0LcJLqbBmaGUft1e9Mm8HV",
              "id": "0LcJLqbBmaGUft1e9Mm8HV",
              "name": "ABBA",
              "type": "artist",
              "uri": "spotify:artist:0LcJLqbBmaGUft1e9Mm8HV"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "disc_number": 1,
          "duration_ms": 294720,
          "explicit": false,
          "external_ids": {
            "isrc": "SEAYD8001020"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/3oEkrIfXfSh9zGnE7eBzSV"
          },
          "href": "https://api.spotify.com/v1/tracks/3oEkrIfXfSh9zGnE7eBzSV",
          "id": "3oEkrIfXfSh9zGnE7eBzSV",
          "is_local": false,
          "is_playable": true,
          "name": "The Winner Takes It All",
          "popularity": 82,
          "preview_url": null,
          "track_number": 2,
          "type": "track",
          "uri": "spotify:track:3oEkrIfXfSh9zGnE7eBzSV"
        },
        {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV"
                },
                "href": "https://api.spotify.com/v1/artists/0LcJLqbBmaGUft1e9Mm8HV",
                "id": "0LcJLqbBmaGUft1e9Mm8HV",
                "name": "ABBA",
                "type": "artist",
                "uri": "spotify:artist:0LcJLqbBmaGUft1e9Mm8HV"
              }
            ],
            "available_markets": [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/7iLuHJkrb9KHPkMgddYigh"
            },
            "href": "https://api.spotify.com/v1/albums/7iLuHJkrb9KHPkMgddYigh",
            "id": "7iLuHJkrb9KHPkMgddYigh",
            "images": [
              {
                "height": 640,
                "width": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b273aa22899360d8ba6704732dec"
              },
              {
                "height": 300,
                "width": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e02aa22899360d8ba6704732dec"
              },
              {
                "height": 64,
                "width": 64,
                "url": "https://i.scdn.co/image/ab67616d00004851aa22899360d8ba6704732dec"
              }
            ],
            "is_playable": true,
            "name": "Voulez-Vous",
            "release_date": "1979",
            "release_date_precision": "year",
            "total_tracks": 13,
            "type": "album",
            "uri": "spotify:album:7iLuHJkrb9KHPkMgddYigh"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV"
              },
              "href": "https://api.spotify.com/v1/artists/0LcJLqbBmaGUft1e9Mm8HV",
              "id": "0LcJLqbBmaGUft1e9Mm8HV",
              "name": "ABBA",
              "type": "artist",
              "uri": "spotify:artist:0LcJLqbBmaGUft1e9Mm8HV"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "disc_number": 1,
          "duration_ms": 309173,
          "explicit": false,
          "external_ids": {
            "isrc": "SEAYD7901020"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/17OqI90oTFZ3J8PVu6j07V"
          },
          "href": "https://api.spotify.com/v1/tracks/17OqI90oTFZ3J8PVu6j07V",
          "id": "17OqI90oTFZ3J8PVu6j07V",
          "is_local": false,
          "is_playable": true,
          "name": "Voulez-Vous",
          "popularity": 75,
          "preview_url": null,
          "track_number": 2,
          "type": "track",
          "uri": "spotify:track:17OqI90oTFZ3J8PVu6j07V"
        },
        {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV"
                },
                "href": "https://api.spotify.com/v1/artists/0LcJLqbBmaGUft1e9Mm8HV",
                "id": "0LcJLqbBmaGUft1e9Mm8HV",
                "name": "ABBA",
                "type": "artist",
                "uri": "spotify:artist:0LcJLqbBmaGUft1e9Mm8HV"
              }
            ],
            "available_markets": [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/5gSBDA6ufk8UZejT4XR7av"
            },
            "href": "https://api.spotify.com/v1/albums/5gSBDA6ufk8UZejT4XR7av",
            "id": "5gSBDA6ufk8UZejT4XR7av",
            "images": [
              {
                "height": 640,
                "width": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b27311c24dc7f5ef909381c0a7d6"
              },
              {
                "height": 300,
                "width": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e0211c24dc7f5ef909381c0a7d6"
              },
              {
                "height": 64,
                "width": 64,
                "url": "https://i.scdn.co/image/ab67616d0000485111c24dc7f5ef909381c0a7d6"
              }
            ],
            "is_playable": true,
            "name": "Waterloo",
            "release_date": "1974",
            "release_date_precision": "year",
            "total_tracks": 14,
            "type": "album",
            "uri": "spotify:album:5gSBDA6ufk8UZejT4XR7av"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV"
              },
              "href": "https://api.spotify.com/v1/artists/0LcJLqbBmaGUft1e9Mm8HV",
              "id": "0LcJLqbBmaGUft1e9Mm8HV",
              "name": "ABBA",
              "type": "artist",
              "uri": "spotify:artist:0LcJLqbBmaGUft1e9Mm8HV"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "disc_number": 1,
          "duration_ms": 168960,
          "explicit": false,
          "external_ids": {
            "isrc": "SEAYD7415010"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/3Dy4REq8O09IlgiwuHQ3sk"
          },
          "href": "https://api.spotify.com/v1/tracks/3Dy4REq8O09IlgiwuHQ3sk",
          "id": "3Dy4REq8O09IlgiwuHQ3sk",
          "is_local": false,
          "is_playable": true,
          "name": "Waterloo",
          "popularity": 76,
          "preview_url": null,
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:3Dy4REq8O09IlgiwuHQ3sk"
        }
      ]
    }
  }

  export default mockResponse;